name: Generar repos.json

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositori
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.GH_TOKEN }}

      - name: Instal·la Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instal·la axios
        run: npm install axios

      - name: Executa script de generació
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node scripts/generate-json.js

      - name: Fes commit dels resultats
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/repos.json
          git commit -m "Actualitza repos.json" || echo "Sense canvis"
          git push
