
name: Genera JSON d'Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install axios
      - name: Executa el script
        run: node scripts/generate-json.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit i push del JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/repos.json
          git commit -m "Actualitza repos.json"
          git push
